from hsr.views.login import login
from hsr.views.logout import logout
from hsr.views.static import static
from hsr.views.change_password import change_password
from hsr.views.museum_objects import museum_objects
from hsr.views.museum_object import museum_object
from hsr.views.bio_individuals import bio_individuals
from hsr.views.bio_individual import bio_individual
from hsr.views.user_management import user_management 
from hsr.views.edit_user import edit_user
from hsr.views.delete_user import delete_user
from hsr.views.edit_bio import edit_bio
